sudo: required
language: go
branches:
  only:
  - master
go:
- '1.9'
env:
- CLOUDSDK_CORE_DISABLE_PROMPTS=1
#cache:
#  directories:
#  - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_bd75f0e62987_key -iv $encrypted_bd75f0e62987_iv
  -in client-secret.json.enc -out client-secret.json -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && \
  chmod +x kubectl && sudo mv kubectl /usr/local/bin/
- kubectl config view
install:
- go get -v .
script:
- go test -v ./...
services:
- docker
before_deploy:
  #- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # - source /home/travis/google-cloud-sdk/path.bash.inc
  - kubectl --help
after_success:
- bash ./deployment/travis/deploy
