sudo: false
language: go
os: linux
branches:
  only:
  - master
go:
  - 1.9.x
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=client-secret.json
    - PROJECT_NAME=kubernetes-example-199908
    - CLUSTER_NAME=cluster-1
    - CLOUDSDK_COMPUTE_ZONE=us-central1-a
    - DOCKER_IMAGE_NAME=hello-app
    - KUBE_DEPLOYMENT_NAME=hello-app
    - KUBE_DEPLOYMENT_CONTAINER_NAME=hello-app-golang
    - CLOUD_SQL_ICN=kubernetes-example-199908:us-central1:sql-example
services:
- docker
cache:
 directories:
  - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_bd75f0e62987_key -iv $encrypted_bd75f0e62987_iv
  -in client-secret.json.enc -out ${GOOGLE_APPLICATION_CREDENTIALS} -d
- gcloud auth activate-service-account --key-file ${GOOGLE_APPLICATION_CREDENTIALS}
- gcloud container clusters get-credentials cluster-1 --zone us-central1-a --project kubernetes-example-199908
install:
- go get -v .
- go get github.com/mattes/migrate
- go get gopkg.in/testfixtures.v2
- go get github.com/pressly/goose/cmd/goose
script:
- go test -v ./...
before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
deploy:
  provider: script
  script: bash ./.deployment/travis/deploy-dev
  on:
    branch: master

#  provider: script
#  script: bash ./.deployment/travis/deploy-dev
#  on:
#    branch: develop
