sudo: false
language: go
branches:
  only:
  - master
go:
- '1.9'
env:
- CLOUDSDK_CORE_DISABLE_PROMPTS=1
#cache:
#  directories:
#  - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_bd75f0e62987_key -iv $encrypted_bd75f0e62987_iv
  -in client-secret.json.enc -out client-secret.json -d
- gcloud version
- gcloud components update kubectl || true
- curl https://sdk.cloud.google.com | bash
- bash -l ./gcloud.sh version
- bash -l ./gcloud.sh components update kubectl
#- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
#  fi
- kubectl config view
install:
- go get -v .
script:
- go test -v ./...
services:
- docker
before_deploy:
  #- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # - source /home/travis/google-cloud-sdk/path.bash.inc
  - kubectl --help
after_success:
- bash ./deployment/travis/deploy
