language: go

branches:
  only:
    - master

go:
  - "1.9"

install:
  - go get -v .

script:
  - go test -v ./...

after_success:
  - 'bash ./travis/deploy'
#script:
#   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
#   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
