sudo: required
language: go
os: linux
branches:
  only:
  - master
go:
  - 1.9.x
#cache:
# directories:
#  - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_bd75f0e62987_key -iv $encrypted_bd75f0e62987_iv
  -in client-secret.json.enc -out client-secret.json -d
- curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
- mkdir -p .bin; mv ./kubectl .bin/kubectl && chmod +x .bin/kubectl
- export PATH="$TRAVIS_BUILD_DIR/.bin:$PATH"
- wget https://cdn.rawgit.com/Mirantis/kubeadm-dind-cluster/master/fixed/dind-cluster-v1.7.sh && chmod +x dind-cluster-v1.7.sh && ./dind-cluster-v1.7.sh up
- export PATH="$HOME/.kubeadm-dind-cluster:$PATH"
install:
- go get -v .
script:
- go test -v ./...
services:
- docker
before_deploy:
  #- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # - source /home/travis/google-cloud-sdk/path.bash.inc
  - kubectl --help
after_success:
- bash ./.deployment/travis/deploy
