language: go

branches:
  only:
    - master

go:
  - "1.9"

# Cache our Gcloud SDK between commands
cache:
  directories:
  - "$HOME/google-cloud-sdk/"

before_install:
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in client-secret.json.enc -out client-secret.json -d
  - if [ ! -d ${HOME}/google-cloud-sdk ]; then
       curl https://sdk.cloud.google.com | bash;
    fi
  # Here we use the decrypted service account credentials to authenticate the command line tool
  - gcloud auth activate-service-account --key-file client-secret.json

install:
  - go get -v .

script:
  - go test -v ./...

services:
  - docker

after_success:
  - 'bash ./travis/deploy'
#script:
#   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
#   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
