FROM golang:1.9

ENV APP_ENV dev

ADD . /go/src/github.com/golang/example/outyet

WORKDIR /go/src/github.com/golang/example/outyet

RUN go get . && \
    go get github.com/canthefason/go-watcher && \
    go get github.com/mattes/migrate && \
    go install github.com/canthefason/go-watcher/cmd/watcher && \
    go get -u github.com/pressly/goose/cmd/goose

EXPOSE 8080

ENTRYPOINT watcher