apiVersion: v1
kind: Pod
metadata:
  name: golang-pod
  labels:
    name: golang-pod
spec:
  containers:
  - name: golang
    image: chapal/hello-world-service:v7
    ports:
    - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: entrypoint
  labels:
    name: entrypoint
spec:
  type: LoadBalancer
  selector:
    name: golang-pod
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 8080