apiVersion: v1
kind: Service
metadata:
  name: go-balancer
  labels:
      app: hello-world
spec:
  type: LoadBalancer
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080