apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: hello-world
    name: mysql-service
spec:
  ports:
  - port: 3306
  selector:
    name: mysql-pod
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      name: mysql-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: mysql-pod
    spec:
      containers:
      - image: mysql:5.6
        name: mysql-foo
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        ports:
        - containerPort: 3306
          name: mysql-pod
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim