apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod-2
  labels:
    name: mysql-pod-2
spec:
  containers:
  - name: mysql-bar
    image: mysql:5.6
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "root"
    volumeMounts:
    - name: mysql-persistent-storage
      mountPath: /var/lib/mysql
  volumes:
  - name: mysql-persistent-storage
    persistentVolumeClaim:
      claimName: mysql-volume-2
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service-2
  labels:
    name: mysql-service-2
spec:
  ports:
  - port: 3306
  selector:
    name: mysql-pod-2
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
