kind: Namespace
apiVersion: v1
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
  namespace: dev
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: hello-app
  type: LoadBalancer
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello-app-deployment
  namespace: dev
  labels:
    app: hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hello-app
  template:
    metadata:
      labels:
        name: hello-app
    spec:
      containers:
      - name: golang-container
        image: gcr.io/kubernetes-example-199908/hello-app:v1
        env:
        - name: HTTP_ADDRESS
          value: ":8080"
        - name: APP_ENV
          value: "dev"
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10