apiVersion: batch/v1
kind: Job
metadata:
  name: hello-app-migrations
  namespace: dev
spec:
  template:
    spec:
      containers:
        - name: hello-app-golang-job
          image: gcr.io/kubernetes-example-199908/hello-app:06f841a
#          command: ['goose', '-dir', 'migrations', 'mysql', '"${DB_USER}:${DB_PASS}@tcp(${DB_HOST}:3306)/${DB_NAME}"', 'up']
#          command: ["sh", "-c", "tail -f /dev/null"]
          command: ['go', 'run', 'command/migrate.go']
          env:
          - name: HTTP_ADDRESS
            value: ":8080"
          - name: APP_ENV
            value: "dev"
          - name: DB_HOST
            value: "localhost"
          - name: DB_NAME
            value: "test"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: password
      restartPolicy: Never
  backoffLimit: 1
