#!/bin/bash

if ([ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ])
then
  VERSION=$(git rev-parse --short master)
  go build -ldflags "-X main.version=${VERSION}" -o hello-world .
  docker build -t gcr.io/${PROJECT_NAME}/${DOCKER_IMAGE_NAME}:${VERSION} .
  gcloud --quiet config set project ${PROJECT_NAME}
  gcloud --quiet config set container/cluster ${CLUSTER_NAME}
  gcloud --quiet config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
  gcloud --quiet container clusters get-credentials ${CLUSTER_NAME}

  gcloud docker -- push gcr.io/${PROJECT_NAME}/${DOCKER_IMAGE_NAME}:${VERSION}
  kubectl --namespace=dev set image deployment/hello-app-deployment golang-container=gcr.io/kubernetes-example-199908/hello-app:${VERSION}
  echo "Website deployed on ${VERSION}"
else
  echo "Build successful, but not publishing!"
fi
