#!/bin/bash

if ([ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ])
then
  VERSION=$(git rev-parse --short master)
  docker build -t gcr.io/${PROJECT_NAME}/${DOCKER_IMAGE_NAME}:${VERSION} .
  gcloud --quiet config set project ${PROJECT_NAME}
  gcloud --quiet config set container/cluster ${CLUSTER_NAME}
  gcloud --quiet config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
  gcloud --quiet container clusters get-credentials ${CLUSTER_NAME}

  gcloud docker -- push gcr.io/${PROJECT_NAME}/${DOCKER_IMAGE_NAME}:${VERSION}
  curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
  mkdir -p .bin; mv ./kubectl .bin/kubectl && chmod +x .bin/kubectl
  export PATH="$TRAVIS_BUILD_DIR/.bin:$PATH"
  kubectl --namespace=dev set image deployment/${KUBE_DEPLOYMENT_NAME} ${KUBE_DEPLOYMENT_CONTAINER_NAME}=gcr.io/${PROJECT_NAME}/${DOCKER_IMAGE_NAME}:${VERSION}
  echo "Website deployed on ${VERSION}"
else
  echo "Build successful, but not publishing!"
fi
