#!/bin/bash

if ([ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ])
then
  VERSION=$(git rev-parse --short HEAD)
  go build -ldflags "-X main.version=${VERSION}" -o hello-world .
  docker build -t gcr.io/kubernetes-example-199908/hello-app:${VERSION} .
  gcloud docker -- push gcr.io/kubernetes-example-199908/hello-app:${VERSION}
  echo "Website deployed on ${VERSION}"
else
  echo "Build successful, but not publishing!"
fi
